/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NovoFrame2;

import br.ufrpe.assistech.dados.IRepositorioCliente;
import br.ufrpe.assistech.dados.RepositorioCliente;
import br.ufrpe.assistech.entityBeans.Cliente;
import br.ufrpe.assistech.exceptions.CNEException;
import br.ufrpe.assistech.negocio.Fachada;
import br.ufrpe.assistech.negocio.IFachada;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alheirosb
 */
public class CadastrePanel extends javax.swing.JPanel {

    /**
     * Creates new form Panel1
     */
    
   /* IFachada fachada = Fachada.getInstance();
    IRepositorioCliente cliente = RepositorioCliente.getInstance();
    private Cliente c = new Cliente();
     */       
    public CadastrePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtCampoEnderecoRua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLblDadosEndereco = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtCampoEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtCampoNome = new javax.swing.JTextField();
        jtxtCampoTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtCampoNumeroResidencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtCampoEnderecoBairro = new javax.swing.JTextField();
        jtxtCampoCelular = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jtxtCampoEnderecoRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 83, 310, -1));

        jLabel6.setText("Rua:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, -1, -1));

        jLblDadosEndereco.setText("Dados de endereço");
        add(jLblDadosEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 63, -1, -1));

        jLabel3.setText("E-mail:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jtxtCampoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCampoEmailActionPerformed(evt);
            }
        });
        add(jtxtCampoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 37, 226, -1));

        jLabel2.setText("Nome:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jtxtCampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCampoNomeActionPerformed(evt);
            }
        });
        add(jtxtCampoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 11, 490, -1));
        add(jtxtCampoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 37, 144, -1));

        jLabel4.setText("Fone:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 40, -1, -1));

        jtxtCampoNumeroResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCampoNumeroResidenciaActionPerformed(evt);
            }
        });
        add(jtxtCampoNumeroResidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 52, -1));

        jLabel7.setText("Nº:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));
        add(jtxtCampoEnderecoBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 83, 162, -1));
        add(jtxtCampoCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 37, 243, -1));

        jLabel9.setText("Bairro:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 86, -1, -1));

        jLabel8.setText("Cel:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 40, -1, -1));

        jLabel1.setText("CPF:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 14, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 11, 162, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCampoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCampoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCampoEmailActionPerformed

    private void jtxtCampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCampoNomeActionPerformed

    private void jtxtCampoNumeroResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCampoNumeroResidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCampoNumeroResidenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblDadosEndereco;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jtxtCampoCelular;
    private javax.swing.JTextField jtxtCampoEmail;
    private javax.swing.JTextField jtxtCampoEnderecoBairro;
    private javax.swing.JTextField jtxtCampoEnderecoRua;
    private javax.swing.JTextField jtxtCampoNome;
    private javax.swing.JTextField jtxtCampoNumeroResidencia;
    private javax.swing.JTextField jtxtCampoTelefone;
    // End of variables declaration//GEN-END:variables
}
